version: '3'
services:

  gateway:
    build: src
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
    ports:
      - "127.0.0.1:5000:5000"
    depends_on:
      - elasticsearch

  keybase:
    build: src
    environment:
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      - "FLOCK_KEYBASE=1"
    env_file:
      - keybase.env
    depends_on:
      - elasticsearch

  kibana:
    image: "kibana:7.6.2"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  elasticsearch:
    image: "elasticsearch:7.6.2"
    environment:
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - ./data/elasticsearch:/usr/share/elasticsearch/data
