version: '3'
services:
  admin:
    build: admin
    ports:
      - "127.0.0.1:5000:5000"
    volumes:
      - /data
      - ./admin:/app
  tor:
    build: tor
    ports:
      - "9051"
  elasticsearch:
    image: "elasticsearch:6.5.4@sha256:7053b3979a1dd709f2a225d52bc53622714790b13d88cf08164d252291ab8b61"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - /usr/share/elasticsearch/data
  kibana:
    image: "kibana:6.5.4@sha256:106ff4a8c691936d4de7e2aba289939624ec75b26746d5660201f47c0afe2d73"
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
