version: '3'
services:

  test-gateway:
    build: ./src
    environment:
      - ELASTICSEARCH_HOSTS=http://test-elasticsearch:9200

  test-elasticsearch:
    image: "elasticsearch:7.3.0"
    environment:
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - transport.host=localhost
      - ELASTICSEARCH_HOSTS=http://test-elasticsearch:9200
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
