version: 2

workflows:
  version: 2
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/python:3.7.2

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build containers
          command: docker build -t gateway gateway

      - run:
          name: Start containers
          command: |
            docker network create testnet
            docker run -d --net testnet --name elasticsearch -e xpack.security.enabled=false -e transport.host=localhost elasticsearch:6.6.0
            docker run -d --net testnet --name gateway gateway

      - run:
         name: Wait for elasticsearch to be available
         command: docker exec -it gateway ./wait_for_es.sh

      - run:
          name: Run unit tests
          command: docker exec -it gateway pipenv run python -m pytest
