version: 2

workflows:
  version: 2
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/python:3.7.2

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Start elasticsearch container, and update /etc/hosts
          command: |
            set -x
            sudo sh -c 'echo "127.0.0.1 elasticsearch" >> /etc/hosts'
            docker run -p 9200:9200 -d elasticsearch:6.5.4

      - run:
          name: Install gateway dependencies
          command: |
            cd gateway
            pip install pipenv
            pipenv install --dev

      - run:
          name: Run unit tests
          command: |
            cd gateway
            export FLASK_APP=gateway
            pipenv run python -m pytest
