version: 2

workflows:
  version: 2
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/python:3.7.2

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build containers
          command: docker build -t gateway gateway

      - run:
          name: Start containers
          command: |
            docker network create testnet
            docker run -d --net testnet --name test-elasticsearch -e xpack.security.enabled=false -e transport.host=localhost elasticsearch:6.6.0@sha256:ed1f27b9a16dc29d19fc607a1e6e281d1ddf83d81734427d895f5b91c23a6ee5
            docker run -d --net testnet --name test-gateway -e ELASTICSEARCH_HOSTS=http://test-elasticsearch:9200 gateway

      - run:
         name: Wait for elasticsearch to be available
         command: docker exec -it test-gateway ./wait_for_es.sh

      - run:
          name: Run unit tests
          command: docker exec -it test-gateway pipenv run python -m pytest
