version: 2

workflows:
  version: 2
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/python:3.7.2

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Build containers
          command: docker build -t server src

      - run:
          name: Start containers
          command: |
            docker-compose -f tests.yml up -d

      - run:
          name: List containers
          command: |
            sleep 5
            docker container ls

      - run:
         name: Wait for elasticsearch to be available
         command: docker exec -it test-server ./wait_for_es.sh

      - run:
          name: Run unit tests
          command: docker exec -it test-server pipenv run python -m pytest -vvv
