version: 2

workflows:
  version: 2
  test:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: circleci/python:3.7.2

    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: Start containers
          command: |
            docker-compose -f tests.yml up -d &&
            docker exec -it project_test-server_1 ./wait_for_es.sh

      - run:
          name: Run unit tests
          command: docker exec -it project_test-server_1 pipenv run python -m pytest -vvv
